### ISSUE TITLE
can2040 for micropython

### ISSUE THREAD

**Issue by Eminemchik** [KevinOConnor/can2040#28]
Hi, thanks for the great library!
Are there plans for a micropython version?

**Comment by bjpirt** [comment]
I came here wondering the same thing - would be an amazing add-on to the MicroPython ecosystem!

**Comment by KevinOConnor** [comment]
FWIW, I don't know of anyone currently working on a MicroPython implementation.

Cheers,
-Kevin

**Comment by bjpirt** [comment]
@KevinOConnor Given that you can configure the RP2040 state machines directly from Python code, I was wondering if you know of any blockers to porting your code to pure Python (given you know the code best!), rather than compiling the C code into MicroPython.

I wouldn't mind giving it a try but knowing it's theoretically possible would be helpful before embarking on such a mission

**Comment by KevinOConnor** [comment]
Alas, it's not something I've looked at, so I'm not able to provide any meaningful advice.

-Kevin

**Comment by ferranmercader** [comment]
@Eminemchik @bjpirt , I'm came here also wondering the same thing. I've found this repository:
https://github.com/kentindell/canis-can-sdk

Did you finally find any solution?

**Comment by Eminemchik** [comment]
@ferranmercader I ended up using the MCP2515 in my project. I used the code from https://www.waveshare.com/wiki/Pico-CAN-B as an example.
